import styles from "../styles/style.module.css";
import IconLogo from "../../assets/IconLogo.svg";

const TermsOfService = () => {
  return (
    <div>
      <h1 className={"mt-12 text-center text-3xl text-bold"}>Terms of Service</h1>

      <div className={`${styles.contentContainer} ${styles.termsContent}`}>
        <p className={styles.effectiveDate}>Effective Date: Jan 1, 2025</p>

        <p>
          Welcome to WhatAgent, a wholly owned division of StarFish Apps, Inc.
          These Terms of Service (TOS) govern your access to and use of our
          Large Language Model (LLM)-based services, applications, and any
          related tools, websites, or platforms (collectively, the services). By
          accessing or using the Services, you agree to comply with and be bound
          by these Terms. If you do not agree to these Terms, you may not use
          the Services.
        </p>

        <h2>1. Definitions</h2>
        <p>
          LLM refers to the Large Language Model that provides responses to user
          inputs based on machine learning algorithms.
        </p>
        <p>
          User refers to any individual or entity accessing or using the
          Services.
        </p>
        <p>
          Content refers to any text, images, audio, video, data, or other
          materials generated by or submitted to the Services.
        </p>

        <h2>2. Eligibility</h2>
        <p>
          You must be at least 18 years old (or the age of majority in your
          jurisdiction) to use the Services. If you are using the Services on
          behalf of an entity, you represent and warrant that you have the
          authority to bind that entity to these Terms.
        </p>

        <h2>3. Acceptable Use Policy</h2>
        <p>By using the Services, you agree to:</p>
        <ul>
          <li>
            Use the Services only for lawful purposes and in compliance with all
            applicable laws and regulations.
          </li>
          <li>
            Not use the Services to generate or disseminate illegal, harmful, or
            misleading content, including but not limited to:
            <ul>
              <li>Hate speech, harassment, or threats.</li>
              <li>Misinformation, deepfakes, or deceptive content.</li>
              <li>
                Content that violates intellectual property rights or privacy
                laws.
              </li>
              <li>
                Child exploitation, violent, or sexually explicit material.
              </li>
            </ul>
          </li>
          <li>
            Not attempt to reverse-engineer, scrape, modify, or manipulate the
            Services in any unauthorized manner.
          </li>
          <li>
            Not use automated systems (e.g., bots, scrapers) to interact with
            the Services unless explicitly permitted.
          </li>
          <li>
            Not impersonate others or misrepresent your affiliation with any
            person or entity.
          </li>
        </ul>
        <p>
          We reserve the right to suspend or terminate access to any user who
          violates this policy.
        </p>

        <h2>4. User-Generated Content</h2>

        <h3>4.1 Responsibility for Content</h3>
        <p>
          You are solely responsible for any content you submit, generate, or
          distribute using the Services. We do not endorse or assume liability
          for user-generated content.
        </p>

        <h3>4.2 License to Use Content</h3>
        <p>
          By using the Services, you grant us a non-exclusive, worldwide,
          royalty-free license to store, process, and display the content you
          provide for the purpose of operating and improving the Services.
        </p>

        <h3>4.3 Content Moderation</h3>
        <p>
          We reserve the right (but are not obligated) to review, modify, or
          remove any content that violates these Terms or is otherwise deemed
          inappropriate.
        </p>

        <h2>5. Privacy and Data Usage</h2>
        <p>
          Your use of the Services is also governed by our Privacy Policy, which
          explains how we collect, use, and protect your data. By using the
          Services, you consent to such data practices.
        </p>
        <p>
          We may log interactions with the Service for the purpose of improving
          performance, security, and functionality.
        </p>
        <p>
          We do not store or retain personally identifiable information beyond
          what is necessary for operation.
        </p>
        <p>
          We may use aggregated and anonymized data for research, analytics, and
          model improvements.
        </p>
        <p>
          For more details, please review our{" "}
          <a href="/privacy">Privacy Policy</a>.
        </p>

        <h2>6. Intellectual Property</h2>

        <h3>6.1 Ownership</h3>
        <p>
          The Services, including all underlying technology, code, and models,
          are owned or licensed by us and protected under applicable
          intellectual property laws.
        </p>
        <p>Users do not acquire ownership of any part of the Service.</p>

        <h3>6.2 Feedback and Improvements</h3>
        <p>
          If you provide us with suggestions or feedback, you grant us a
          perpetual, irrevocable, royalty-free license to use and implement your
          feedback without obligation.
        </p>

        <h2>7. Service Availability and Limitations</h2>
        <p>
          The Services are provided on an as-is and if available basis with no
          guarantees of uptime, performance, or reliability.
        </p>
        <p>
          We may update, modify, or discontinue the Services at any time without
          prior notice.
        </p>
        <p>
          We are not responsible for errors, interruptions, or inaccuracies in
          generated content.
        </p>

        <h2>8. Limitation of Liability</h2>
        <p>To the fullest extent permitted by law:</p>
        <p>
          We are not liable for any indirect, incidental, consequential, or
          punitive damages arising from the use of the Services.
        </p>
        <p>
          We make no warranties regarding the accuracy, completeness, or
          usefulness of generated content.
        </p>
        <p>
          You assume full responsibility for any decisions made based on the
          information provided by the Services.
        </p>
        <p>
          If you are dissatisfied with the Services, your sole remedy is to stop
          using them.
        </p>

        <h2>9. Indemnification</h2>
        <p>
          You agree to defend, indemnify, and hold harmless ShareBrain, Starfish
          Apps, Inc. and its affiliates, officers, employees, and agents from
          any claims, liabilities, damages, losses, or expenses arising from:
        </p>
        <ul>
          <li>Your use of the Services.</li>
          <li>Your violation of these Terms or applicable laws.</li>
          <li>
            Any third-party claims related to content you generate or submit.
          </li>
        </ul>

        <h2>10. Third-Party Services and Links</h2>
        <p>
          The Services may include integrations or links to third-party
          platforms. We do not endorse, control, or assume liability for any
          third-party content.
        </p>

        <h2>11. Modifications to the Terms</h2>
        <p>
          We reserve the right to update or modify these Terms at any time.
          Changes will be effective immediately upon posting. Your continued use
          of the Services constitutes acceptance of the revised Terms.
        </p>

        <h2>12. Governing Law and Dispute Resolution</h2>
        <p>
          These Terms are governed by the laws of The State of Delaware without
          regard to conflicts of law principles. Any disputes shall be resolved
          through binding arbitration or in courts located in The State of
          Delaware.
        </p>

        <h2>13. Termination</h2>
        <p>
          We may suspend or terminate your access to the Services at any time
          if:
        </p>
        <ul>
          <li>You violate these Terms.</li>
          <li>We discontinue the Services.</li>
        </ul>
        <p>
          Termination does not affect any rights or obligations accrued prior to
          termination.
        </p>

        <h2>14. Contact Information</h2>
        <p>
          If you have any questions or concerns about these Terms, please
          contact us at:
        </p>
        <p>Email: tom@whatagent.net</p>
        <p>
          Website:{" "}
          <a
            href="https://whatagent.net"
            target="_blank"
            rel="noopener noreferrer"
          >
            https://whatagent.net
          </a>
        </p>
      </div>
    </div>
  );
};

export default TermsOfService;
